version: '3'
services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile  # Use your custom PHP Dockerfile here
    ports:
      - "9000"  # PHP-FPM port, no need to expose to host since NGINX will proxy requests
    volumes:
      - .:/var/www/html  # Mount project directory to container
    depends_on:
      - db

  web:
    image: nginx:latest
    ports:
      - "8000:80"  # Map port 8000 on host to port 80 in NGINX container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX configuration file

    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root  # Set the root password here
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
